name: merge2dev
on:
  push:
    branches-ignore:
      - main
      - dev
permissions:
  contents: read
jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./tweet22/Server/tweet22.Server.csproj
    - name: Build
      run: dotnet build ./tweet22/Server/tweet22.Server.csproj --no-restore
    - name: Test
      run: dotnet test ./tweet22/Server/tweet22.Server.csproj --no-build --verbosity normal
  clear-pr-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get PR numbers
        run: |
          sudo apt-get -y install jq
          ticket_number=$(gh pr list --repo repasscloud/tweet22 --json number | jq '.[].number')
          if [ -n "$ticket_number" ]; then
            echo "PR numbers exist: $ticket_number"
            gh pr close "$ticket_number" --repo repasscloud/tweet22
          else
            echo "No PR numbers exist"
            # Do nothing
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
  auto-pr:
    needs:
      - clear-pr-queue
      - dotnet-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create pull request
        run: gh pr create -B dev -H ${{ github.ref }} --title 'Auto PR from branch to DEV' --body 'Automatically created by gh-actions.'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
  auto-merge:
    needs: [ "auto-pr" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: merge pull request
        run: gh pr merge --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

